trigger: 
- feature/*
- main

pool: MyLaptopAgent

variables:
  workDir: '$(System.DefaultWorkingDirectory)/environments/dev'

stages:
- stage: Build
  displayName: Build
  jobs:       
  - job: TerraformInitPlan
    displayName: Terraform Init and Plan Job
    steps: 
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(workDir)
        backendServiceArm: 'connection1'
        backendAzureRmStorageAccountName: 'ymystorage8745'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: $(workDir)
        environmentServiceNameAzureRM: 'connection1'

- stage: Scanning
  displayName: Scanning
  jobs: 
  - job: TFSecScanningJob
    displayName: TFSEC Scanning
    pool: Default
    steps:
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
        dir: $(workDir)

  - job: TfLintScanningJob
    displayName: TFLINT Scanning
    pool: Default
    steps:
     - task: PowerShell@2
      continueOnError: true
      inputs:
        targetType: 'inline'
        script: |
          winget install TerraformLinters.tflint     
          ls   
          tflint
        errorActionPreference: 'continue'        
        workingDirectory: $(workDir)

- stage: Deploy
  displayName: Deploy
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs: 
  - job: ManualValidation
    displayName: Manual Validation kardo Please
    pool: server
    steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'yashwant@gmail.com'
        approvers: 'yashwant@gmail.com'
        instructions: 'Plan check...'

  - job: TerraformApply
    displayName: Terraform Apply wala Job
    dependsOn: ManualValidation
    pool: Default
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(workDir)
        backendServiceArm: 'connection1'
        backendAzureRmStorageAccountName: 'ymystorage8745'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: $(workDir)
        environmentServiceNameAzureRM: 'connection1'

